### ISSUE TITLE
EPIC: Аудит задач и заметки по развитию VB 2.0

### ISSUE THREAD

**Issue by allustin** [silverbulleters/vanessa-behavior-new#13]
сводная задача по формированию backlog'а на 2017-2018 годы

за основу взяты https://github.com/silverbulleters/vanessa-behavior/issues
приоритетов нет, однако структура соответствует категориям задач

выполняется в рамках изменения процесса производства Vanessa-Behavior

## Рабочий процесс

- [ ] полный git-flow - master, develop, features/, hotfix и т.д.
- [ ] переехать на разработку в новом репозитории (vflow) без бинарных файлов
- [ ] добавить CLA и автоматический CI для PR-xx - положением о контрибьютинге (cla)
- [ ] объем кода участвующего в проверке поведения (code coverage)
- [ ] управление техническим долгом (sonar) - снижением копипаста в том числе и в шагах проверки, а также алгоритмическая чистота

## Развитие функционала

- [ ] финализация фунционала "дымовой проверки" на BDD 
- [ ] дымовые CRUD операции
- [ ] при парсинге фич выводить список ролей для поиска дубликатов
- [ ] локализовать интерфейс и частично отрефакторить глоссарий
- [ ] локализовать ключевые слова с других языков
- [ ] отображать измененные файлы функциональности если они находятся под управлением DCVS
- [ ] управление приоритетами сниппетов
- [ ] управлением дубликатами сниппетов
- [ ] сниппеты для работы с внешними обработками и отчетами в режиме БСП
- [ ] сниппеты на английском и других языках
- [ ] сниппеты проверки текстовых полей
- [ ] автоподстановка исключений при кодировании средствами VSCode (подсказка по assertam)
- [ ] человекочитаемые исключения в стиле GoBehave
- [ ] рефакторинг форматеров junit и cucumber.json
- [ ] повысить эргономичность в частности произвести рефакторинг дерева
- [ ] использование горячих клавиш
- [ ] ожидание от данных в виде библиотечных шагов
- [ ] ожидание от формы и её подчиненных элементов
- [ ] отладка по шагам
- [ ] управление комплектом test-client'ов
- [ ] распределение тест-клиентов по ролям в шапке файлов функциональности
- [ ] искать дубликаты заголовков элементов в режиме тест-клиента
- [ ] выдавать ошибку в файлах описания функциональности имеющим только контекст
- [ ] реализовать аудит множеств - "шаги" минус "сниппеты" на предмет сниппетов без шагов
- [ ] глобальные перехваты включая ПередНачаломВыполнения и ПослеНачалаВыполнения
- [ ] интеграционные проверки поведения "Когда в УТ - Тогда в БП"
- [ ] облако тегов и статистика по ним
- [ ] многострочные параметры
- [ ] сниппеты работы с оповещениями форм
- [ ] сниппеты для работы с табличными полями
- [ ] человекочитаемые ошибки при запуске из консоли (связана с vflow-vrun)
- [ ] генерация областей и комментариев в обработках для удобного программирования шагов
- [ ] экспорт структуры сценария для включения в интегральный сценарий
- [ ] генератор UML и EPC для визуального отображения поведения
- [ ] видеоинструкция на языке файла функциональности
- [ ] переходы клавишами в режиме тестклиент в списках и тому подобном
- [ ] ожидания от изменений заголовков форм
- [ ] сниппеты для мультистрокового выделения
- [ ] тэгирование примеров сценариев
- [ ] JSON схема для параметров запуска
- [ ] эргономика дерева - сворачивание, поиск, фильтрация и т.д.

## Изменения поведения старого функционала

- [ ] изменение вариантов распространения бинарных файлов - не через git, а c помощью пакетных менеджеров

## Документирование

- [ ] рефакторинг документации контрибьютора
- [ ] рефакторинг автоматических инструкций
- [ ] простой how-to
- [ ] документирование готовых библиотечных шагов
- [ ] описание процесса отладки шагов
- [ ] описание процедуры отладки и подачи багов в 1С по работе тест-клиента
- [ ] имплементировать pickles и его аналог для linux с картинками
- [ ] правила создания "красивой инструкции"
- [ ] документирование правил локализации croudin
- [ ] документировать тэги и сценарии их использования
- [ ] документировать варианты структур каталогов `features`

## Архитектурные решения и пилотирование функционала

- [ ] сформировать виденье по архитектуре Behavior и xUnit https://github.com/silverbulleters/vanessa-behavior/issues/39
- [ ] рассмотреть возможность портирования Gherkin C# через NativeAPI в режиме C#/Mono
- [ ] адаптер к 1Script - возможно на основе https://github.com/silverbulleters-forks/oscript-behavior
- [ ] секция тогда в формате JSON
- [ ] непротиворечивое синтаксису Gherkin параметризированные сценарии
- [ ] меньше переключений между контекстами фичи и шагов проверки https://github.com/silverbulleters/vanessa-behavior/issues/351 как пример и прецедент
- [ ] генерация и перегенерация в режиме watch
- [ ] структура сценария и таблицы
- [ ] использование аналога тест-клиента на обычных формах https://github.com/silverbulleters/vanessa-behavior/issues/430
- [ ] i18n Gherkin, Snippets and UI - обертки и адаптеры как вариант

## Неудобства (включая ошибки, которых я уверен нет)

- [ ] интерактивный импорт, экспорт .conf.json
- [ ] исправить недочеты при чтении .conf.json
- [ ] экранировать кавычки в названиях окон
- [ ] длинные пути файлов функциональности и каталогов шагов определений
- [ ] отчет Аллюр может не до конца сформироваться если упала платформа (дай ей бог здоровья)
